blank_issues_enabled: false
contact_links:
  - name: Support question
    url: https://github.com/typephp-php/typephp/discussions/new?category=q-a
    about: Please open a new discussion instead. Thank you.